sonar.projectKey=dvi-happy-dee-all-service
sonar.sources=src/.
sonar.host.url=http://localhost:9000
# Windows
sonar.login=sqp_4700fdae886bd98ab54f1ecdf34e95e4d29244dd

sonar.exclusions=**/*.test.ts
sonar.test.inclusions=**/*.test.ts
# sonar.test.exclusions=**/*.cy.ts, **/*.cy.tsx

# reports + test coverage
# sonar.coverage.jacoco.xmlReportPaths=./reports/**/*.xml
# sonar.javascript.lcov.reportPaths=./reports/**/*.xml
# sonar.typescript.lcov.reportPaths=./reports/**/*.xml