export const COLOR_OPTIONS = [
  // Reds
  { value: '#8b0000', label: 'Darkred' },
  { value: '#800000', label: 'Maroon' },
  { value: '#b22222', label: 'Firebrick' },
  { value: '#a52a2a', label: 'Brown' },
  { value: '#cd5c5c', label: 'Indianred' },
  { value: '#dc143c', label: 'Crimson' },
  { value: '#ff0000', label: 'Red' },
  { value: '#f08080', label: 'Lightcoral' },
  { value: '#bc8f8f', label: 'Rosybrown' },
  // Orange-reds
  { value: '#fa8072', label: 'Salmon' },
  { value: '#ff6347', label: 'Tomato' },
  { value: '#ff7f50', label: 'Coral' },
  { value: '#ff4500', label: 'Orangered' },
  { value: '#e9967a', label: 'Darksalmon' },
  { value: '#ffa07a', label: 'Lightsalmon' },
  // Oranges / Browns
  { value: '#8b4513', label: 'Saddlebrown' },
  { value: '#a0522d', label: 'Sienna' },
  { value: '#d2691e', label: 'Chocolate' },
  { value: '#ff8c00', label: 'Darkorange' },
  { value: '#cd853f', label: 'Peru' },
  { value: '#f4a460', label: 'Sandybrown' },
  { value: '#ffa500', label: 'Orange' },
  { value: '#deb887', label: 'Burlywood' },
  { value: '#d2b48c', label: 'Tan' },
  // Light oranges / creams
  // { value: '#ffdab9', label: 'Peachpuff' },
  // { value: '#ffe4c4', label: 'Bisque' },
  // { value: '#ffdead', label: 'Navajowhite' },
  // { value: '#ffebcd', label: 'Blanchedalmond' },
  // { value: '#ffe4b5', label: 'Moccasin' },
  // { value: '#ffefd5', label: 'Papayawhip' },
  // { value: '#f5deb3', label: 'Wheat' },
  // { value: '#faebd7', label: 'Antiquewhite' },
  // Yellows
  { value: '#b8860b', label: 'Darkgoldenrod' },
  { value: '#daa520', label: 'Goldenrod' },
  { value: '#ffd700', label: 'Gold' },
  { value: '#bdb76b', label: 'Darkkhaki' },
  // { value: '#f0e68c', label: 'Khaki' },
  // { value: '#eee8aa', label: 'Palegoldenrod' },
  // { value: '#fafad2', label: 'Lightgoldenrodyellow' },
  // { value: '#fff8dc', label: 'Cornsilk' },
  // { value: '#fffacd', label: 'Lemonchiffon' },
  // { value: '#ffff00', label: 'Yellow' },
  // { value: '#ffffe0', label: 'Lightyellow' },
  // { value: '#f5f5dc', label: 'Beige' },
  // { value: '#fffff0', label: 'Ivory' },
  // Yellow-greens
  { value: '#808000', label: 'Olive' },
  { value: '#556b2f', label: 'Darkolivegreen' },
  { value: '#6b8e23', label: 'Olivedrab' },
  { value: '#9acd32', label: 'Yellowgreen' },
  { value: '#adff2f', label: 'Greenyellow' },
  { value: '#7fff00', label: 'Chartreuse' },
  { value: '#7cfc00', label: 'Lawngreen' },
  // Greens
  { value: '#006400', label: 'Darkgreen' },
  { value: '#008000', label: 'Green' },
  { value: '#228b22', label: 'Forestgreen' },
  { value: '#2e8b57', label: 'Seagreen' },
  { value: '#3cb371', label: 'Mediumseagreen' },
  { value: '#8fbc8f', label: 'Darkseagreen' },
  { value: '#32cd32', label: 'Limegreen' },
  // { value: '#90ee90', label: 'Lightgreen' },
  // { value: '#98fb98', label: 'Palegreen' },
  { value: '#00ff00', label: 'Lime' },
  // Spring greens / Aquamarines
  { value: '#00ff7f', label: 'Springgreen' },
  { value: '#00fa9a', label: 'Mediumspringgreen' },
  { value: '#66cdaa', label: 'Mediumaquamarine' },
  // { value: '#7fffd4', label: 'Aquamarine' },
  // Cyans / Teals
  { value: '#20b2aa', label: 'Lightseagreen' },
  { value: '#40e0d0', label: 'Turquoise' },
  { value: '#48d1cc', label: 'Mediumturquoise' },
  { value: '#2f4f4f', label: 'Darkslategray' },
  { value: '#008b8b', label: 'Darkcyan' },
  { value: '#008080', label: 'Teal' },
  { value: '#00ced1', label: 'Darkturquoise' },
  { value: '#5f9ea0', label: 'Cadetblue' },
  { value: '#00ffff', label: 'Aqua' },
  // { value: '#afeeee', label: 'Paleturquoise' },
  // { value: '#e0ffff', label: 'Lightcyan' },
  // Near-white greens / cyans
  // { value: '#f0fff0', label: 'Honeydew' },
  // { value: '#f5fffa', label: 'Mintcream' },
  // { value: '#f0ffff', label: 'Azure' },
  // Sky blues
  // { value: '#b0e0e6', label: 'Powderblue' },
  // { value: '#add8e6', label: 'Lightblue' },
  { value: '#00bfff', label: 'Deepskyblue' },
  // { value: '#87ceeb', label: 'Skyblue' },
  // { value: '#87cefa', label: 'Lightskyblue' },
  { value: '#4682b4', label: 'Steelblue' },
  { value: '#1e90ff', label: 'Dodgerblue' },
  { value: '#6495ed', label: 'Cornflowerblue' },
  // { value: '#b0c4de', label: 'Lightsteelblue' },
  // { value: '#708090', label: 'Slategray' },
  // { value: '#778899', label: 'Lightslategray' },
  // Blues
  { value: '#4169e1', label: 'Royalblue' },
  { value: '#483d8b', label: 'Darkslateblue' },
  { value: '#6a5acd', label: 'Slateblue' },
  { value: '#7b68ee', label: 'Mediumslateblue' },
  { value: '#191970', label: 'Midnightblue' },
  { value: '#000080', label: 'Navy' },
  { value: '#00008b', label: 'Darkblue' },
  { value: '#0000cd', label: 'Mediumblue' },
  { value: '#0000ff', label: 'Blue' },
  // Near-white blues
  // { value: '#f0f8ff', label: 'Aliceblue' },
  // { value: '#f8f8ff', label: 'Ghostwhite' },
  // { value: '#e6e6fa', label: 'Lavender' },
  // Blue-violets / Indigos / Purples
  { value: '#8a2be2', label: 'Blueviolet' },
  { value: '#663399', label: 'Rebeccapurple' },
  { value: '#4b0082', label: 'Indigo' },
  { value: '#9400d3', label: 'Darkviolet' },
  { value: '#9932cc', label: 'Darkorchid' },
  { value: '#9370db', label: 'Mediumpurple' },
  { value: '#ba55d3', label: 'Mediumorchid' },
  // Magentas
  { value: '#800080', label: 'Purple' },
  { value: '#8b008b', label: 'Darkmagenta' },
  { value: '#da70d6', label: 'Orchid' },
  { value: '#dda0dd', label: 'Plum' },
  { value: '#ff00ff', label: 'Magenta' },
  { value: '#ee82ee', label: 'Violet' },
  { value: '#d8bfd8', label: 'Thistle' },
  // Pinks
  { value: '#c71585', label: 'Mediumvioletred' },
  { value: '#ff1493', label: 'Deeppink' },
  { value: '#ff69b4', label: 'Hotpink' },
  { value: '#db7093', label: 'Palevioletred' },
  // { value: '#fff0f5', label: 'Lavenderblush' },
  // { value: '#ffe4e1', label: 'Mistyrose' },
  // { value: '#ffc0cb', label: 'Pink' },
  // { value: '#ffb6c1', label: 'Lightpink' },
  // Near-white warm tones
  // { value: '#fff5ee', label: 'Seashell' },
  // { value: '#faf0e6', label: 'Linen' },
  // { value: '#fffaf0', label: 'Floralwhite' },
  // { value: '#fdf5e6', label: 'Oldlace' },
  // Neutrals (dark to light)
  // { value: '#000000', label: 'Black' },
  // { value: '#696969', label: 'Dimgray' },
  // { value: '#808080', label: 'Gray' },
  // { value: '#a9a9a9', label: 'Darkgray' },
  // { value: '#c0c0c0', label: 'Silver' },
  // { value: '#d3d3d3', label: 'Lightgray' },
  // { value: '#dcdcdc', label: 'Gainsboro' },
  // { value: '#f5f5f5', label: 'Whitesmoke' },
  // { value: '#fffafa', label: 'Snow' },
  // { value: '#ffffff', label: 'White' },
]
