import { IconName } from 'lucide-react/dynamic'

export const ICON_OPTIONS: { name: IconName; label: string }[] = [
  // Tech / AI
  { name: 'bot', label: 'Bot' },
  { name: 'cpu', label: 'CPU' },
  { name: 'command', label: 'Command' },
  { name: 'terminal', label: 'Terminal' },
  { name: 'code', label: 'Code' },
  { name: 'code-2', label: 'Code 2' },
  { name: 'database', label: 'Database' },
  { name: 'server', label: 'Server' },
  { name: 'hard-drive', label: 'Hard Drive' },
  { name: 'cloud', label: 'Cloud' },
  { name: 'wifi', label: 'Wifi' },
  { name: 'monitor', label: 'Monitor' },
  { name: 'laptop', label: 'Laptop' },
  { name: 'smartphone', label: 'Smartphone' },
  { name: 'git-branch', label: 'Git Branch' },
  { name: 'blocks', label: 'Blocks' },
  { name: 'layers', label: 'Layers' },
  { name: 'audio-waveform', label: 'Waveform' },
  // Space / Energy
  { name: 'rocket', label: 'Rocket' },
  { name: 'sparkles', label: 'Sparkles' },
  { name: 'flame', label: 'Flame' },
  { name: 'zap', label: 'Zap' },
  { name: 'star', label: 'Star' },
  { name: 'sun', label: 'Sun' },
  { name: 'moon', label: 'Moon' },
  { name: 'globe', label: 'Globe' },
  { name: 'globe-2', label: 'Globe 2' },
  // Business / Work
  { name: 'briefcase-business', label: 'Briefcase' },
  { name: 'building-2', label: 'Building' },
  { name: 'users', label: 'Users' },
  { name: 'user', label: 'User' },
  { name: 'user-check', label: 'User Check' },
  { name: 'handshake', label: 'Handshake' },
  { name: 'graduation-cap', label: 'Graduation' },
  { name: 'presentation', label: 'Presentation' },
  { name: 'clipboard', label: 'Clipboard' },
  { name: 'clipboard-list', label: 'Clipboard List' },
  { name: 'calendar', label: 'Calendar' },
  { name: 'calendar-check', label: 'Calendar Check' },
  { name: 'clock', label: 'Clock' },
  { name: 'target', label: 'Target' },
  { name: 'trophy', label: 'Trophy' },
  { name: 'award', label: 'Award' },
  { name: 'medal', label: 'Medal' },
  // Finance
  { name: 'circle-dollar-sign', label: 'Dollar' },
  { name: 'wallet', label: 'Wallet' },
  { name: 'credit-card', label: 'Credit Card' },
  { name: 'banknote', label: 'Banknote' },
  { name: 'trending-up', label: 'Trending Up' },
  { name: 'trending-down', label: 'Trending Down' },
  { name: 'bar-chart-2', label: 'Bar Chart' },
  { name: 'line-chart', label: 'Line Chart' },
  { name: 'pie-chart', label: 'Pie Chart' },
  // Security
  { name: 'shield-check', label: 'Shield' },
  { name: 'lock', label: 'Lock' },
  { name: 'key', label: 'Key' },
  { name: 'fingerprint', label: 'Fingerprint' },
  { name: 'eye', label: 'Eye' },
  // Communication
  { name: 'mail', label: 'Mail' },
  { name: 'phone', label: 'Phone' },
  { name: 'message-square', label: 'Message' },
  { name: 'message-circle', label: 'Message Circle' },
  { name: 'bell', label: 'Bell' },
  { name: 'share-2', label: 'Share' },
  { name: 'link', label: 'Link' },
  // Files / Docs
  { name: 'file-text', label: 'File Text' },
  { name: 'folder', label: 'Folder' },
  { name: 'folder-open', label: 'Folder Open' },
  { name: 'archive', label: 'Archive' },
  { name: 'bookmark', label: 'Bookmark' },
  { name: 'tag', label: 'Tag' },
  { name: 'gallery-vertical-end', label: 'Gallery' },
  // Creative / Media
  { name: 'palette', label: 'Palette' },
  { name: 'pen', label: 'Pen' },
  { name: 'pen-tool', label: 'Pen Tool' },
  { name: 'image', label: 'Image' },
  { name: 'camera', label: 'Camera' },
  { name: 'video', label: 'Video' },
  { name: 'music', label: 'Music' },
  { name: 'headphones', label: 'Headphones' },
  // Navigation
  { name: 'home', label: 'Home' },
  { name: 'map', label: 'Map' },
  { name: 'map-pin', label: 'Map Pin' },
  { name: 'compass', label: 'Compass' },
  { name: 'navigation', label: 'Navigation' },
  { name: 'search', label: 'Search' },
  { name: 'filter', label: 'Filter' },
  // Nature
  { name: 'leaf', label: 'Leaf' },
  { name: 'tree-pine', label: 'Tree' },
  { name: 'flower-2', label: 'Flower' },
  { name: 'mountain', label: 'Mountain' },
  { name: 'waves', label: 'Waves' },
  { name: 'snowflake', label: 'Snowflake' },
  { name: 'cloud-rain', label: 'Rain' },
  // Misc
  { name: 'settings-2', label: 'Settings' },
  { name: 'heart', label: 'Heart' },
  { name: 'diamond', label: 'Diamond' },
  { name: 'gem', label: 'Gem' },
  { name: 'crown', label: 'Crown' },
  { name: 'shield', label: 'Shield Plain' },
  { name: 'package', label: 'Package' },
  { name: 'box', label: 'Box' },
  { name: 'grid-2x2', label: 'Grid' },
  { name: 'layout-dashboard', label: 'Dashboard' },
  { name: 'life-buoy', label: 'Life Buoy' },
  { name: 'lightbulb', label: 'Lightbulb' },
  { name: 'puzzle', label: 'Puzzle' },
  { name: 'infinity', label: 'Infinity' },
  { name: 'feather', label: 'Feather' },
  { name: 'anchor', label: 'Anchor' },
  { name: 'flag', label: 'Flag' },
  { name: 'bolt', label: 'Bolt' },
]
